import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased `}

      >
        <header style={{ background: "green", width: "100%", padding: "2%", height: "20%" }}>
          <h1 className="text-2xl text-white text-center">Header</h1>
        </header>
        <footer className="fixed w-full bottom-0 bg-gray-900 text-gray-300 ">


          {/* Footer Bottom */}
          <div className="  p-4 text-center text-xl text-white">
            Footer
          </div>
        </footer>

        {children}
      </body>
    </html>
  );
}
